version: '3.7'

services:
  db:
    image: postgres:14
    privileged: true
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: "education_services"
    ports:
      - "5440:5432"
    volumes:
      - ./var/data/postgresql:/var/lib/postgresql
  backend:
    build: .
    volumes:
      - .:/backend_service
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: redis:latest
    ports:
      - "6391:6379"