version: '3.7'

services:
  db:
    image: postgres:latest
    privileged: true
    restart: always
    ports:
      - "5440:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: "education_services"
  backend:
    build: .
    volumes:
      - .:/backend_service
    ports:
      - "1568:8080"
    depends_on:
      - db
  redis:
    image: redis:latest
    ports:
      - "6391:6379"