version: '3.7'

services:
  db:
    image: postgres:14
    privileged: true
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: "education_services"
    ports:
      - "5440:5432"
    volumes:
      - pg_data:/var/lib/postgresql
  backend:
    build: .
    command: bash -c "python /backend_service/manage.py migrate --noinput &&
             python /backend_service/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/backend_service
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: redis:latest
    ports:
      - "6391:6379"
  celery:
    build: .
    command: celery -A education_services worker -l info
    links:
      - redis
    depends_on:
      - db
      - redis
volumes:
  pg_data: