version: '3.7'

services:
  db:
    image: postgres:latest
    privileged: true
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ''
      POSTGRES_PASSWORD: ''
      POSTGRES_DB: "education_services"
