# Generated by Django 4.0.3 on 2022-03-10 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trainingapp', '0004_question_answer_alter_answer_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_right_answers', models.PositiveSmallIntegerField(verbose_name='Количество верных ответов')),
                ('count_wrong_answers', models.PositiveSmallIntegerField(verbose_name='Количество неверных ответов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменения')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingapp.topic', verbose_name='Тема')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
