# Generated by Django 4.0.3 on 2022-03-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0005_resultanswers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultanswers',
            options={'verbose_name': 'Результат тестирования', 'verbose_name_plural': 'Результаты тестирования'},
        ),
        migrations.AlterField(
            model_name='resultanswers',
            name='count_right_answers',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество верных ответов'),
        ),
        migrations.AlterField(
            model_name='resultanswers',
            name='count_wrong_answers',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество неверных ответов'),
        ),
    ]
