# Generated by Django 4.0.3 on 2022-03-12 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0006_alter_resultanswers_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
    ]
