# Generated by Django 4.0.3 on 2022-03-12 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0007_remove_answer_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer',
            new_name='answers',
        ),
    ]
