# Generated by Django 4.0.3 on 2022-03-12 11:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingapp', '0008_rename_answer_question_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultanswers',
            name='list_questions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), blank=True, null=True, size=None, verbose_name='Список id вопросов'),
        ),
    ]
